name: "Build - action"

on: [push, pull_request]

jobs:
  build-docker-image:
    name: "Reconciliation Docker"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run build.bash
        env:
          GHCR_OWNER: ${{secrets.GHCR_OWNER}}
          GHCR_PAT: ${{secrets.GHCR_PAT}}
          GHCR_USER: ${{secrets.GHCR_USER}}
        run: ./build.bash
